# Generated by Django 5.0.1 on 2024-01-14 22:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arcondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('RF', 'Refrigeração'), ('EL', 'Elétrica'), ('TL', 'Telemetria'), ('IR', 'Irradiação')], max_length=2)),
                ('status', models.CharField(choices=[('F', 'Funcionando'), ('S', 'StandyBy'), ('DF', 'Defeito'), ('M', 'Manutenção')], max_length=2)),
                ('tipo_equipamento', models.CharField(choices=[('AR', 'Arcondicionado'), ('CB', 'Cabo')], max_length=120)),
                ('potencia', models.IntegerField()),
                ('tensao', models.IntegerField()),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='arcondicionado/documentos'), blank=True, null=True, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='arcondicionado/images'), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
